import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "surface-container-low": "#eff4ff",
                "on-tertiary-fixed": "#131b2e",
                "tertiary-fixed-dim": "#bec6e0",
                "outline-variant": "#bec8d2",
                "on-primary-fixed-variant": "#004c6e",
                "secondary-fixed": "#ffe083",
                "secondary": "#735c00",
                "error": "#ba1a1a",
                "inverse-primary": "#89ceff",
                "primary": "#006591",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed-variant": "#3f465c",
                "on-tertiary": "#ffffff",
                "on-background": "#0b1c30",
                "surface-container": "#e5eeff",
                "primary-container": "#0ea5e9",
                "on-error-container": "#93000a",
                "surface-bright": "#f8f9ff",
                "on-secondary-fixed": "#231b00",
                "primary-fixed-dim": "#89ceff",
                "on-tertiary-container": "#2b3347",
                "tertiary-fixed": "#dae2fd",
                "secondary-fixed-dim": "#eec200",
                "surface-dim": "#cbdbf5",
                "on-secondary-fixed-variant": "#574500",
                "secondary-container": "#fed01b",
                "outline": "#6e7881",
                "inverse-surface": "#213145",
                "on-primary-fixed": "#001e2f",
                "primary-fixed": "#c9e6ff",
                "on-secondary-container": "#6f5900",
                "on-secondary": "#ffffff",
                "surface-tint": "#006591",
                "on-primary": "#ffffff",
                "surface": "#f8f9ff",
                "surface-container-highest": "#d3e4fe",
                "on-surface-variant": "#3e4850",
                "on-surface": "#0b1c30",
                "surface-container-high": "#dce9ff",
                "inverse-on-surface": "#eaf1ff",
                "surface-variant": "#d3e4fe",
                "tertiary": "#565e74",
                "background": "#f8f9ff",
                "tertiary-container": "#939bb3",
                "on-primary-container": "#003751",
                "on-error": "#ffffff",
                "error-container": "#ffdad6"
            },
            fontFamily: {
                sans: ['Atkinson Hyperlegible Next', 'Inter', ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Public Sans", "sans-serif"],
                "display-lg": ["Public Sans", "sans-serif"],
                "display-lg-mobile": ["Public Sans", "sans-serif"],
                "headline-md": ["Public Sans", "sans-serif"],
                "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
                "body-md": ["Atkinson Hyperlegible Next", "sans-serif"],
                "label-md": ["Atkinson Hyperlegible Next", "sans-serif"],
                "label-sm": ["Atkinson Hyperlegible Next", "sans-serif"],
                "card-title": ["Inter", "sans-serif"],
                "button-text": ["Inter", "sans-serif"],
                "label-xs": ["Inter", "sans-serif"],
            },
            fontSize: {
                "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
                "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "card-title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
                "button-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
                "label-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
            },
            spacing: {
                "base": "4px",
                "gutter": "24px",
                "container-max": "1280px",
                "section-gap-md": "80px",
                "section-gap-lg": "120px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "stack-lg": "32px",
                "xs": "4px",
                "sm": "8px",
                "md": "16px",
                "lg": "24px",
                "xl": "32px",
                "header-height": "64px",
                "sidebar-width": "360px",
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            }
        },
    },

    plugins: [forms],
};
